title = "root@highpackets:~#"

# The URL the site will be built for
base_url = "https://highpackets.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# theme
theme = "dose"

# taxonomies
taxonomies = [
    { name = "tags", feed = true },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "visual-studio-dark"

[extra]
# Put all your custom variables here
social_media = [
    { name = "GitHub", url = "https://github.com/highpackets" },
    { name = "Telegram", url = "https://t.me/highpackets" }
]
default_theme = "dark" # or "light"
